### ISSUE TITLE
Login with user HR Manager does not work after seeding

### ISSUE THREAD

**Issue by nekromoff** [kmanjari/hrms#33]
using: `email@gmail.com`
and: `123456` for password

Login form is submitted, but user is returned to the login screen without any error.

**Comment by noadek** [comment]
Try using a virtual host. Since laravel uses a public folder called 'public' the login form submits to itself which is a your <host>/folder/public. The .htacess file will treat this url as a directory and just return the index page again. 

Hence the rule 
```
# Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
```
will take effect.

Either remove the rule or setup a virtual host. Although I would suggest using the virtual host.

Hope this helps!

**Comment by khanof89** [comment]
I have added the changes in the login form in case there is some kind of errors it will show you on the page itself. As noadek said use a virtual host for laravel projects
